name: Build and Release PDF (XeLaTeX)

on:
  push:
    tags:
      - '*'  # Trigger on any tag

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Fetch all tags
       run: git fetch --tags --force

    - name: Extract tag and commit hash
       run: |
         echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
         echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Update version in colophon
        run: ./gitinfo.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile LaTeX with XeLaTeX
      uses: dante-ev/latex-action@latest
      with:
        root_file: simetrije.tex

    - name: Create GitHub Release and upload PDF
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: simetrije.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
